# Generated by Django 4.0 on 2022-01-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Econtact', models.CharField(max_length=10)),
                ('Eid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
